# Generated by Django 4.2.4 on 2023-09-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer_fee',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
