# Generated by Django 4.2.4 on 2023-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='overview',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
