# Generated by Django 4.2.4 on 2024-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_selleraccountbalance_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentwithdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('wallete', 'Wallete')], default='bank_transfer', max_length=254),
        ),
    ]
