# Generated by Django 4.2.4 on 2024-03-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentwithdrawal_withdrawal_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentwithdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], default='bank_transfer', max_length=255),
        ),
    ]
