# Generated by Django 4.2.4 on 2024-03-03 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_upi_id_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upi_id',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upi_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
