# Generated by Django 4.2.4 on 2024-03-03 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0009_alter_bank_user_alter_upi_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], default='bank_transfer', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_method', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
