# Generated by Django 4.2.4 on 2024-03-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_alter_order_transaction'),
        ('payments', '0011_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.order'),
        ),
    ]
