# Generated by Django 4.2.4 on 2024-03-15 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0018_alter_order_transaction'),
        ('payments', '0012_refund_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refund',
            new_name='Refund_details',
        ),
    ]
