# Generated by Django 4.2.4 on 2024-03-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_alter_order_transaction'),
        ('payments', '0013_rename_refund_refund_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund_details',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.order'),
        ),
    ]
