# Generated by Django 4.2.4 on 2024-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_refund_details_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund_details',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
