# Generated by Django 4.2.4 on 2023-08-27 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('search_tags', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('delivery_time', models.PositiveIntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days')], default=1)),
                ('revisions', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('source_file', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='', max_length=200)),
                ('question_type', models.CharField(choices=[('text', 'Text Answer'), ('textarea', 'Text Area'), ('choices', 'Multiple Choice')], max_length=20)),
                ('text', models.TextField(default='', max_length=200)),
                ('choices', models.CharField(default='', max_length=10)),
                ('allow_multiple_selection', models.BooleanField(default=False)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('delivery_time', models.PositiveIntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days')], default=1)),
                ('revisions', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('source_file', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('video', models.FileField(upload_to='videos/')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.PositiveIntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days')], default=1)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('delivery_time', models.PositiveIntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days')], default=1)),
                ('revisions', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('source_file', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
    ]
