# Generated by Django 4.2.4 on 2023-08-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video',
        ),
    ]
