# Generated by Django 4.2.4 on 2023-08-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_remove_gallery_image_gallery_image1_gallery_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraService',
        ),
    ]
