# Generated by Django 4.2.4 on 2023-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_delete_extraservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='title',
        ),
        migrations.AddField(
            model_name='overview',
            name='titleOverview',
            field=models.TextField(default='titleOverview', max_length=100),
            preserve_default=False,
        ),
    ]
