# Generated by Django 4.2.4 on 2023-08-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_alter_overview_titleoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
