# Generated by Django 4.2.4 on 2023-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_overview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
