# Generated by Django 4.2.4 on 2023-08-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_alter_overview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicpackage',
            old_name='delivery_time',
            new_name='Basic_delivery_time',
        ),
        migrations.RenameField(
            model_name='basicpackage',
            old_name='description',
            new_name='Basic_description',
        ),
        migrations.RenameField(
            model_name='basicpackage',
            old_name='price',
            new_name='Basic_price',
        ),
        migrations.RenameField(
            model_name='basicpackage',
            old_name='revisions',
            new_name='Basic_revisions',
        ),
        migrations.RenameField(
            model_name='basicpackage',
            old_name='source_file',
            new_name='Basic_source_file',
        ),
        migrations.RenameField(
            model_name='basicpackage',
            old_name='title',
            new_name='Basic_title',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='delivery_time',
            new_name='Premium_delivery_time',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='description',
            new_name='Premium_description',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='price',
            new_name='Premium_price',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='revisions',
            new_name='Premium_revisions',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='source_file',
            new_name='Premium_source_file',
        ),
        migrations.RenameField(
            model_name='premiumpackage',
            old_name='title',
            new_name='Premium_title',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='delivery_time',
            new_name='Standard_delivery_time',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='description',
            new_name='Standard_description',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='price',
            new_name='Standard_price',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='revisions',
            new_name='Standard_revisions',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='source_file',
            new_name='Standard_source_file',
        ),
        migrations.RenameField(
            model_name='standardpackage',
            old_name='title',
            new_name='Standard_title',
        ),
    ]
