# Generated by Django 4.2.4 on 2023-09-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_alter_basicpackage_basic_revisions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpackage',
            name='Premium_revisions',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), ('unlimited', 'unlimited')], default=1),
        ),
        migrations.AlterField(
            model_name='standardpackage',
            name='Standard_revisions',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), ('unlimited', 'unlimited')], default=1),
        ),
    ]
