# Generated by Django 4.2.4 on 2024-01-07 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_alter_ratingseller_reviewer_and_more'),
        ('Services', '0014_alter_premiumpackage_premium_revisions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='rating',
        ),
        migrations.AddField(
            model_name='overview',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='RatingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('title', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_giver_service', to='Home.userprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received_service', to='Home.userprofile')),
            ],
            options={
                'unique_together': {('seller', 'reviewer')},
            },
        ),
    ]
