# Generated by Django 4.2.4 on 2024-01-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_alter_ratingseller_reviewer_and_more'),
        ('Services', '0015_remove_overview_rating_overview_overall_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ratingservice',
            name='overview',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Services.overview'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingservice',
            unique_together={('overview', 'reviewer')},
        ),
        migrations.RemoveField(
            model_name='ratingservice',
            name='seller',
        ),
    ]
