# Generated by Django 4.2.4 on 2023-10-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender1',
            new_name='sender',
        ),
    ]
