# Generated by Django 4.2.4 on 2023-10-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chating', '0002_rename_sender1_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='message1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='order',
            new_name='order1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='receiver1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='service',
            new_name='service1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='status',
            new_name='status1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='timestamp1',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='video',
            new_name='video1',
        ),
    ]
