# Generated by Django 4.2.4 on 2023-10-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chating', '0003_rename_image_message_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message1',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='order1',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver1',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender1',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='service1',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='status1',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp1',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='video1',
            new_name='video',
        ),
    ]
