# Generated by Django 4.2.4 on 2023-08-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='name1',
        ),
    ]
