# Generated by Django 4.2.4 on 2023-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_name_skill_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me2',
            field=models.TextField(default='about_me2'),
            preserve_default=False,
        ),
    ]
