# Generated by Django 4.2.4 on 2023-08-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_userprofile_about_me2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about_me2',
        ),
    ]
