# Generated by Django 4.2.4 on 2023-08-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_userprofile_about_me2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name1',
            new_name='name',
        ),
    ]
