# Generated by Django 4.2.4 on 2023-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_userprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(choices=[('db', 'Database Management'), ('dn', 'Data Networking')], default='db', max_length=50),
        ),
    ]
