# Generated by Django 4.2.4 on 2023-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_skill_remove_userprofile_skills_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('medium', 'Medium'), ('pro', 'Pro')], max_length=10),
        ),
    ]
