# Generated by Django 4.2.4 on 2023-08-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_language_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('novice', 'Novice'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], max_length=12),
        ),
    ]
