# Generated by Django 4.2.4 on 2024-01-06 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0012_alter_language_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='overall_rating',
        ),
        migrations.CreateModel(
            name='RatingSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('title', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.userprofile')),
            ],
        ),
    ]
