# Generated by Django 4.2.4 on 2024-01-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_remove_userprofile_overall_rating_ratingseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.userprofile'),
        ),
    ]
