# Generated by Django 4.2.4 on 2024-01-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_ratingseller_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingseller',
            name='review_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ratingseller',
            name='total_average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
