# Generated by Django 4.2.4 on 2024-01-06 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0015_alter_ratingseller_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingseller',
            unique_together={('seller', 'reviewer')},
        ),
    ]
