# Generated by Django 4.2.4 on 2024-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_alter_ratingseller_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingseller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
