# Generated by Django 4.2.4 on 2024-01-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_ratingseller_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingseller',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='Home.userprofile'),
        ),
        migrations.AlterField(
            model_name='ratingseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='Home.userprofile'),
        ),
    ]
