# Generated by Django 4.2.4 on 2024-02-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_alter_ratingseller_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/user.png', upload_to='profile_images/'),
        ),
    ]
