# Generated by Django 4.2.13 on 2024-05-20 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('return', 'Return'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('delivery_modifcation_note', models.TextField(blank=True, null=True)),
                ('order_delivered_date', models.DateField(blank=True, null=True)),
                ('delivery_file', models.FileField(blank=True, null=True, upload_to='delivery_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('return', 'Return'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer_1', models.TextField()),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='requirements/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
            ],
        ),
    ]
