# Generated by Django 4.2.4 on 2023-09-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0011_alter_basicpackage_basic_price_and_more'),
        ('Home', '0012_alter_language_proficiency'),
        ('payments', '0003_rename_seller_fee_transaction_service_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.userprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.overview')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer_1', models.TextField()),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='requirements/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
            ],
        ),
    ]
