# Generated by Django 4.2.4 on 2023-09-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status1',
        ),
    ]
