# Generated by Django 4.2.4 on 2023-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_alter_deliverydetails_delivery_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
